# Generated by Django 4.2 on 2023-04-26 11:44

import MyPlantApp.Profile.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=20, validators=[MyPlantApp.Profile.validators.validate_name])),
                ('last_name', models.CharField(max_length=20, validators=[MyPlantApp.Profile.validators.validate_name])),
                ('profile_picture', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
